run:
  tests: false
  timeout: 5m

linters-settings:
  cyclop:
    max-complexity: 12
    skip-tests: true
  funlen:
    lines: 80
  gofumpt:
    extra-rules: true
  gosec:
    excludes:
      - G103

linters:
  enable-all: true
  disable:
    - tenv # deprecated
    - depguard
    - err113
    - exhaustive
    - exhaustruct
    - gci
    - gochecknoglobals
    - mnd
    - nlreturn
    - varnamelen
    - wrapcheck
    - wsl

issues:
  exclude-use-default: false
