version: "2"
run:
  tests: false

formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  settings:
    gofumpt:
      extra-rules: true
  exclusions:
    generated: lax

linters:
  default: all
  disable:
    - depguard
    - err113
    - exhaustive
    - exhaustruct
    - gochecknoglobals
    - mnd
    - nlreturn
    - varnamelen
    - wrapcheck
    - wsl
  settings:
    cyclop:
      max-complexity: 12
    funlen:
      lines: 80
    gosec:
      excludes:
        - G103
  exclusions:
    generated: lax
