version: "2"

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gofumpt:
      extra-rules: true
    gci:
      sections:
        - standard
        - default
        - blank
        - dot
  exclusions:
    generated: lax

linters:
  default: all
  disable:
    - depguard
    - err113
    - exhaustive
    - exhaustruct
    - funcorder
    - funlen
    - gochecknoglobals
    - mnd
    - nlreturn
    - paralleltest
    - varnamelen
    - wrapcheck
    - wsl
  settings:
    cyclop:
      max-complexity: 12
    funlen:
      lines: 80
    gosec:
      excludes:
        - G103
  exclusions:
    generated: lax
    rules:
      - linters:
          - containedctx
        path: retry/retry.go
      - linters:
          - asasalint
        path: _test.go
